import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useApp } from '../context/AppContext';
import { Briefcase, MapPin, DollarSign, Award, Send, ChevronLeft, Plus, Trash2, AlertCircle, CheckCircle2, Sparkles } from 'lucide-react';

export const PostJobPage: React.FC = () => {
  const { addJob, recruiterProfile } = useApp();
  const navigate = useNavigate();

  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState<string | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);

  const handleAutoGenerateDescription = async () => {
    if (!formData.title) {
      setError("Please enter a Job Title first so Gemini knows what to generate.");
      return;
    }
    setError(null);
    setIsGenerating(true);
    try {
      const response = await fetch('/api/gemini/generate-job-description', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          title: formData.title,
          company: formData.company || 'Our Company',
          department: formData.category,
          location: formData.location || 'Remote',
          type: formData.type,
          basicRequirements: skillsRequired.join(', ')
        })
      });
      const data = await response.json();
      if (data.success && data.description) {
        setFormData(prev => ({ ...prev, description: data.description }));
        setSuccess('AI successfully drafted a professional job description for you!');
        setTimeout(() => setSuccess(null), 4000);
      }
    } catch (err) {
      console.error(err);
      setError("Failed to auto-draft job description using AI.");
    } finally {
      setIsGenerating(false);
    }
  };

  const [selectedCurrency, setSelectedCurrency] = useState('₹');
  const [salaryAmount, setSalaryAmount] = useState('');

  const [formData, setFormData] = useState({
    title: '',
    company: recruiterProfile?.companyName || '',
    category: 'Engineering',
    location: '',
    type: 'Full-time' as 'Full-time' | 'Part-time' | 'Contract' | 'Remote' | 'Internship',
    experience: 'Mid-Level',
    description: '',
    companyLogo: recruiterProfile?.companyLogo || ''
  });

  const [skillInput, setSkillInput] = useState('');
  const [skillsRequired, setSkillsRequired] = useState<string[]>(['React', 'TypeScript', 'Tailwind CSS']);

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => {
    const { name, value } = e.target;
    setFormData((prev) => ({ ...prev, [name]: value }));
  };

  const handleAddSkill = (e: React.FormEvent) => {
    e.preventDefault();
    const newSkill = skillInput.trim();
    if (newSkill) {
      const exists = skillsRequired.some(s => s.toLowerCase() === newSkill.toLowerCase());
      if (!exists) {
        setSkillsRequired([...skillsRequired, newSkill]);
      }
      setSkillInput('');
    }
  };

  const handleRemoveSkill = (skillToRemove: string) => {
    setSkillsRequired(skillsRequired.filter((s) => s !== skillToRemove));
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    const finalSalary = `${selectedCurrency} ${salaryAmount.trim()}`;
    if (!formData.title || !formData.company || !formData.location || !salaryAmount.trim() || !formData.description) {
      setError('Please fill out all required fields.');
      return;
    }
    setError(null);

    const payload = {
      ...formData,
      salary: finalSalary,
      skillsRequired
    };

    addJob(payload);
    setSuccess('Job posting published successfully!');
    setTimeout(() => {
      navigate('/manage-jobs');
    }, 1800);
  };

  return (
    <div className="bg-gray-50/50 dark:bg-slate-950 min-h-screen py-8 transition-colors duration-300">
      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 space-y-6">
        
        {/* Breadcrumbs navigation */}
        <button
          onClick={() => navigate('/recruiter-dashboard')}
          className="inline-flex items-center gap-1 text-xs font-bold text-gray-500 hover:text-blue-600 dark:text-gray-400 dark:hover:text-blue-400 cursor-pointer"
        >
          <ChevronLeft className="h-4 w-4" />
          <span>Back to Recruitment Dashboard</span>
        </button>

        <div className="bg-white dark:bg-slate-900 border border-gray-100 dark:border-slate-800 rounded-3xl p-6 md:p-8 shadow-xs space-y-6 transition-colors duration-300">
          <div className="border-b border-gray-50 dark:border-slate-800 pb-4">
            <h1 className="text-xl md:text-2xl font-black text-gray-900 dark:text-white tracking-tight">Post a New Job Opportunity</h1>
            <p className="text-sm text-gray-500 dark:text-gray-400 mt-1">Specify job guidelines, salary packages, and preferred candidate skills.</p>
          </div>

          <form onSubmit={handleSubmit} className="space-y-6">
            {error && (
              <div className="p-4 bg-red-50 dark:bg-red-950/20 border border-red-100 dark:border-red-900/40 rounded-2xl flex items-center gap-3 text-xs text-red-800 dark:text-red-300 animate-pulse">
                <AlertCircle className="h-5 w-5 shrink-0 text-red-500" />
                <span>{error}</span>
              </div>
            )}

            {success && (
              <div className="p-4 bg-emerald-50 dark:bg-emerald-950/10 border border-emerald-100 dark:border-emerald-900/30 rounded-2xl flex items-center gap-3 text-xs text-emerald-800 dark:text-emerald-300">
                <CheckCircle2 className="h-5 w-5 shrink-0 text-emerald-500" />
                <span>{success} Redirecting to your active listings...</span>
              </div>
            )}

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              
              {/* Job Title */}
              <div className="space-y-1.5">
                <label className="text-xs font-bold text-gray-500 dark:text-gray-400 uppercase tracking-wide">Job Title *</label>
                <input
                  type="text"
                  name="title"
                  value={formData.title}
                  onChange={handleInputChange}
                  placeholder="e.g. Senior Frontend Engineer"
                  className="w-full px-4 py-2.5 bg-gray-50 dark:bg-slate-800/60 border border-gray-100 dark:border-slate-700 rounded-xl text-sm focus:outline-none focus:ring-1 focus:ring-blue-500 focus:bg-white dark:focus:bg-slate-800 text-gray-800 dark:text-gray-100"
                  required
                />
              </div>

              {/* Company Name */}
              <div className="space-y-1.5">
                <label className="text-xs font-bold text-gray-500 dark:text-gray-400 uppercase tracking-wide">Company Name *</label>
                <input
                  type="text"
                  name="company"
                  value={formData.company}
                  onChange={handleInputChange}
                  placeholder="e.g. Acme Tech Solutions"
                  className="w-full px-4 py-2.5 bg-gray-50 dark:bg-slate-800/60 border border-gray-100 dark:border-slate-700 rounded-xl text-sm focus:outline-none focus:ring-1 focus:ring-blue-500 focus:bg-white dark:focus:bg-slate-800 text-gray-800 dark:text-gray-100"
                  required
                />
              </div>

              {/* Job Category */}
              <div className="space-y-1.5">
                <label className="text-xs font-bold text-gray-500 dark:text-gray-400 uppercase tracking-wide">Category</label>
                <select
                  name="category"
                  value={formData.category}
                  onChange={handleInputChange}
                  className="w-full px-4 py-2.5 bg-gray-50 dark:bg-slate-800/60 border border-gray-100 dark:border-slate-700 rounded-xl text-sm focus:outline-none focus:ring-1 focus:ring-blue-500 focus:bg-white dark:focus:bg-slate-800 text-gray-800 dark:text-gray-100"
                >
                  <option value="Engineering" className="dark:bg-slate-800">Engineering</option>
                  <option value="Product" className="dark:bg-slate-800">Product</option>
                  <option value="Design" className="dark:bg-slate-800">Design</option>
                  <option value="Marketing" className="dark:bg-slate-800">Marketing</option>
                  <option value="Sales" className="dark:bg-slate-800">Sales</option>
                  <option value="Finance" className="dark:bg-slate-800">Finance</option>
                  <option value="Human Resources" className="dark:bg-slate-800">Human Resources</option>
                </select>
              </div>

              {/* Location */}
              <div className="space-y-1.5">
                <label className="text-xs font-bold text-gray-500 dark:text-gray-400 uppercase tracking-wide">Location *</label>
                <input
                  type="text"
                  name="location"
                  value={formData.location}
                  onChange={handleInputChange}
                  placeholder="e.g. San Francisco, CA (Remote)"
                  className="w-full px-4 py-2.5 bg-gray-50 dark:bg-slate-800/60 border border-gray-100 dark:border-slate-700 rounded-xl text-sm focus:outline-none focus:ring-1 focus:ring-blue-500 focus:bg-white dark:focus:bg-slate-800 text-gray-800 dark:text-gray-100"
                  required
                />
              </div>

              {/* Salary Range */}
              <div className="space-y-1.5">
                <label className="text-xs font-bold text-gray-500 dark:text-gray-400 uppercase tracking-wide">Salary Range *</label>
                <div className="flex gap-2">
                  <select
                    value={selectedCurrency}
                    onChange={(e) => setSelectedCurrency(e.target.value)}
                    className="px-3 py-2.5 bg-gray-50 dark:bg-slate-800/60 border border-gray-100 dark:border-slate-700 rounded-xl text-sm focus:outline-none focus:ring-1 focus:ring-blue-500 focus:bg-white dark:focus:bg-slate-800 text-gray-800 dark:text-gray-100 font-bold"
                  >
                    <option value="₹">₹ (INR)</option>
                    <option value="$">$ (USD)</option>
                    <option value="€">€ (EUR)</option>
                    <option value="£">£ (GBP)</option>
                    <option value="¥">¥ (JPY)</option>
                    <option value="AED">AED</option>
                    <option value="C$">C$ (CAD)</option>
                    <option value="A$">A$ (AUD)</option>
                  </select>
                  <input
                    type="text"
                    value={salaryAmount}
                    onChange={(e) => setSalaryAmount(e.target.value)}
                    placeholder="e.g. 5,00,000 - 12,00,000 or 120k - 150k"
                    className="flex-1 px-4 py-2.5 bg-gray-50 dark:bg-slate-800/60 border border-gray-100 dark:border-slate-700 rounded-xl text-sm focus:outline-none focus:ring-1 focus:ring-blue-500 focus:bg-white dark:focus:bg-slate-800 text-gray-800 dark:text-gray-100 font-medium"
                    required
                  />
                </div>
              </div>

              {/* Employment Type */}
              <div className="space-y-1.5">
                <label className="text-xs font-bold text-gray-500 dark:text-gray-400 uppercase tracking-wide">Employment Type</label>
                <select
                  name="type"
                  value={formData.type}
                  onChange={handleInputChange}
                  className="w-full px-4 py-2.5 bg-gray-50 dark:bg-slate-800/60 border border-gray-100 dark:border-slate-700 rounded-xl text-sm focus:outline-none focus:ring-1 focus:ring-blue-500 focus:bg-white dark:focus:bg-slate-800 text-gray-800 dark:text-gray-100"
                >
                  <option value="Full-time" className="dark:bg-slate-800">Full-time</option>
                  <option value="Part-time" className="dark:bg-slate-800">Part-time</option>
                  <option value="Remote" className="dark:bg-slate-800">Remote</option>
                  <option value="Contract" className="dark:bg-slate-800">Contract</option>
                  <option value="Internship" className="dark:bg-slate-800">Internship</option>
                </select>
              </div>

              {/* Experience Requirement */}
              <div className="space-y-1.5">
                <label className="text-xs font-bold text-gray-500 dark:text-gray-400 uppercase tracking-wide">Experience Requirement</label>
                <select
                  name="experience"
                  value={formData.experience}
                  onChange={handleInputChange}
                  className="w-full px-4 py-2.5 bg-gray-50 dark:bg-slate-800/60 border border-gray-100 dark:border-slate-700 rounded-xl text-sm focus:outline-none focus:ring-1 focus:ring-blue-500 focus:bg-white dark:focus:bg-slate-800 text-gray-800 dark:text-gray-100"
                >
                  <option value="Entry-Level" className="dark:bg-slate-800">Entry-Level</option>
                  <option value="Mid-Level" className="dark:bg-slate-800">Mid-Level</option>
                  <option value="Senior-Level" className="dark:bg-slate-800">Senior-Level</option>
                  <option value="Lead/Manager" className="dark:bg-slate-800">Lead/Manager</option>
                </select>
              </div>

              {/* Company Logo Image URL */}
              <div className="space-y-1.5">
                <label className="text-xs font-bold text-gray-500 dark:text-gray-400 uppercase tracking-wide">Company Logo URL (Optional)</label>
                <input
                  type="url"
                  name="companyLogo"
                  value={formData.companyLogo}
                  onChange={handleInputChange}
                  placeholder="https://images.unsplash.com/... or leave blank"
                  className="w-full px-4 py-2.5 bg-gray-50 dark:bg-slate-800/60 border border-gray-100 dark:border-slate-700 rounded-xl text-sm focus:outline-none focus:ring-1 focus:ring-blue-500 focus:bg-white dark:focus:bg-slate-800 text-gray-800 dark:text-gray-100"
                />
              </div>

            </div>

            {/* Description Area */}
            <div className="space-y-1.5">
              <div className="flex items-center justify-between">
                <label className="text-xs font-bold text-gray-500 dark:text-gray-400 uppercase tracking-wide">Job Description *</label>
                <button
                  type="button"
                  onClick={handleAutoGenerateDescription}
                  disabled={isGenerating}
                  className="px-3.5 py-1.5 bg-blue-600 hover:bg-blue-700 disabled:bg-blue-400 text-white font-bold text-[10px] rounded-lg transition-all cursor-pointer flex items-center gap-1 shadow-xs"
                >
                  {isGenerating ? (
                    <>
                      <div className="h-3 w-3 border border-white border-t-transparent rounded-full animate-spin"></div>
                      <span>Drafting with AI...</span>
                    </>
                  ) : (
                    <>
                      <Sparkles className="h-3 w-3" />
                      <span>Auto-Draft description</span>
                    </>
                  )}
                </button>
              </div>
              <textarea
                name="description"
                rows={7}
                value={formData.description}
                onChange={handleInputChange}
                placeholder="Detail what is required of candidates in this role, general daily workflows, and toolstacks... Or click Auto-Draft above!"
                className="w-full px-4 py-3 bg-gray-50 dark:bg-slate-800/60 border border-gray-100 dark:border-slate-700 rounded-xl text-sm focus:outline-none focus:ring-1 focus:ring-blue-500 focus:bg-white dark:focus:bg-slate-800 resize-none text-gray-800 dark:text-gray-100 font-mono"
                required
              />
            </div>

            {/* Add Target Skills List */}
            <div className="space-y-3">
              <label className="text-xs font-bold text-gray-500 dark:text-gray-400 uppercase tracking-wide block">Skills Required</label>
              
              <div className="flex gap-2">
                <input
                  type="text"
                  value={skillInput}
                  onChange={(e) => setSkillInput(e.target.value)}
                  placeholder="Add skill tag (e.g. Node.js)"
                  className="flex-1 px-4 py-2 bg-gray-50 dark:bg-slate-800/60 border border-gray-100 dark:border-slate-700 rounded-xl text-sm focus:outline-none focus:ring-1 focus:ring-blue-500 text-gray-800 dark:text-gray-100"
                />
                <button
                  type="button"
                  onClick={handleAddSkill}
                  className="px-4 py-2 bg-slate-100 hover:bg-slate-200 dark:bg-slate-800 dark:hover:bg-slate-700 text-slate-800 dark:text-slate-200 text-xs font-bold rounded-xl cursor-pointer flex items-center gap-1"
                >
                  <Plus className="h-4 w-4" />
                  <span>Add</span>
                </button>
              </div>

              {/* Render Skill Tags list */}
              <div className="flex flex-wrap gap-1.5 pt-1">
                {skillsRequired.map((skill, index) => (
                  <span
                    key={index}
                    className="inline-flex items-center gap-1.5 text-xs font-bold text-gray-700 dark:text-gray-300 bg-gray-50 dark:bg-slate-800 border border-gray-100 dark:border-slate-700 px-3 py-1.5 rounded-xl"
                  >
                    <span>{skill}</span>
                    <button
                      type="button"
                      onClick={() => handleRemoveSkill(skill)}
                      className="text-gray-400 dark:text-gray-500 hover:text-red-500 transition-colors"
                    >
                      <Trash2 className="h-3.5 w-3.5" />
                    </button>
                  </span>
                ))}
              </div>
            </div>

            {/* Submit layout */}
            <div className="border-t border-gray-50 dark:border-slate-800 pt-5 flex justify-end gap-3">
              <button
                type="button"
                onClick={() => navigate('/recruiter-dashboard')}
                className="px-5 py-2.5 bg-white dark:bg-slate-900 border border-gray-200 dark:border-slate-700 text-gray-700 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-slate-800 text-xs font-bold rounded-xl cursor-pointer transition-colors"
              >
                Cancel
              </button>
              <button
                type="submit"
                className="px-6 py-2.5 bg-blue-600 hover:bg-blue-700 text-white text-xs font-bold rounded-xl shadow-xs hover:shadow-md transition-all cursor-pointer flex items-center gap-1.5"
              >
                <Send className="h-4 w-4" />
                <span>Post Job Posting</span>
              </button>
            </div>

          </form>

        </div>

      </div>
    </div>
  );
};
